# image will be published to ghcr.io/<user>/<name>
name: server
# description will be included in the image's metadata
description: This is my personal OS image.

# the base image to build on top of (FROM) and the version tag to use
base-image: ghcr.io/ublue-os/base-main
image-version: latest # latest is also supported if you want new updates ASAP

# module configuration, executed in order
# you can include multiple instances of the same module
modules:
  - type: files
    files:
      - source: system
        destination: / # copies files/system/* (* means everything inside it) into your image's root folde
  - type: dnf
    repos:
      files:
        - https://download.docker.com/linux/fedora/docker-ce.repo
        - https://pkgs.tailscale.com/stable/fedora/tailscale.repo
    install:
      packages:
        - tailscale
        - docker-ce
        - docker-ce-cli
        - containerd.io
        - docker-buildx-plugin
        - docker-compose-plugin
  - type: systemd
    system:
      enabled:
        - docker.socket
        - docker.service
  - type: signing 

